### ISSUE TITLE
Unable to change the default Ollama server URL under LLM

### ISSUE THREAD

**Issue by shikhardadhich** [aiplanethub/beyondllm#56]
**Describe the bug**
My Ollama server is running on a different server and I am unable to provide the Ollama base URL in the current code, since the URL is hard coded to _localhost:11434_ 

**To Reproduce**
 Under this file  https://github.com/aiplanethub/beyondllm/blob/main/src/beyondllm/llms/ollama.py
Need to add a parameter to accept the Base_URL 
 import ollama
            self.client = ollama.Client(host='**http://localhost:11434'**)

**Comment by tarun-aiplanet** [comment]
Understood, during initial addition we added for localhost. Do you want to work on this issue by adding client as user input? @shikhardadhich

**Comment by shikhardadhich** [comment]
Sure, I would I add it. @tarun-aiplanet

**Comment by tarun-aiplanet** [comment]
Thank you, I will assign this task to you. You can open PR and link it to this issue

**Comment by tarun-aiplanet** [comment]
Closing this issue, as its been resolved
