### ISSUE TITLE
Dependency Entanglement

### ISSUE THREAD

**Issue by alvinrach** [aiplanethub/beyondllm#74]
I can't solve dependency entanglement when I install beyondllm. To reproduce:

```
python3.10 -m venv venv
source venv/bin/activate
pip install beyondllm llama-index-finetuning llama-index-embeddings-huggingface
```

This will take long time if we install locally.

My OS: Ubuntu 24.04 LTS

-----

Another case if we use google cloud run or streamlit cloud. There's dependency entanglement, for example from cloud run:

2024-08-29 21:08:46.569 ICT
Step #0 - "Buildpack": The conflict is caused by:
2024-08-29 21:08:46.569 ICT
Step #0 - "Buildpack":     The user requested nltk==3.9.1
2024-08-29 21:08:46.569 ICT
Step #0 - "Buildpack":     beyondllm 0.2.2 depends on nltk==3.8.1

![image](https://github.com/user-attachments/assets/47abfc45-d29e-4cae-b08a-b41e34cd8e87)

I tried with newer version also (0.2.3) and more or less, still the same.

**Comment by tarun-aiplanet** [comment]
can you attach your requirements.txt here?

**Comment by alvinrach** [comment]
Hi.. This is the requirements.txt for the cloud run error
https://github.com/alvinrach/rag-agent/blob/003b0a74966642a67ad43c30764a76811a55cbc2/requirements.txt

For the local one, you can try by using only this thing
```
pip install beyondllm llama-index-finetuning llama-index-embeddings-huggingface
```

**Comment by tarun-aiplanet** [comment]
I went through the requirement.txt, the possible reason is because of nltk library. Please directly add the dependency name as attached here:

https://github.com/lucifertrj/pycon-my-2024/blob/main/requirements.txt

Furthermore, as I already mentioned you before, you shouldn't do Fine tuning of embeddings on Streamlit. There is limit of memory and RAM consumption.

**Comment by alvinrach** [comment]
Hi, installed it, looks ok for requiremets you provide, nltk now 3.8.1. I redeploy it on run, there's error.

```
EOFError: EOF when reading a line
Traceback:
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "/workspace/app.py", line 44, in <module>
    embed_model = fine_tuned_model.train([path], "BAAI/bge-small-en-v1.5", llm, "fintune")
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/beyondllm/embeddings/finetune.py", line 73, in train
    embed_model = self.finetune_model(train_file, val_file, model_name)
File "/layers/google.python.pip/pip/lib/python3.10/site-packages/beyondllm/embeddings/finetune.py", line 45, in finetune_model
    user_agree = input("The feature you're trying to use require additional packages. Would you like to install it now? [y/N]: ")
```

Then I think we still need llama-index-embeddings-finetuning so this error won't appear? so I tried it on my local first, still a dependency error. 


```
pip install beyondllm llama-index-embeddings-fastembed llama-index-embeddings-finetuning llama-index-embeddings-huggingface streamlit
```

```
(.testes) ➜  ~ pip install beyondllm llama-index-embeddings-fastembed llama-index-embeddings-finetuning llama-index-embeddings-huggingface streamlit
Collecting beyondllm
  Using cached beyondllm-0.2.3-py3-none-any.whl (54 kB)
Collecting llama-index-embeddings-fastembed
  Using cached llama_index_embeddings_fastembed-0.2.0-py3-none-any.whl (2.7 kB)
ERROR: Could not find a version that satisfies the requirement llama-index-embeddings-finetuning (from versions: none)
ERROR: No matching distribution found for llama-index-embeddings-finetuning
```

**Comment by alvinrach** [comment]
Hi, i found a workaround to solve this.

For google cloud run, just don't use Github Deployment.. Instead, create a Dockerfile with --use-deprecated=legacy-resolver on pip install part.

```
FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt --use-deprecated=legacy-resolver
EXPOSE 8501
CMD ["streamlit", "run", "app.py"]
```

With this, they will ignore the conflicted dependencies.

For the requirements.txt I used,  I installed it one by one on virtual environment. After finished, I just freeze it and use this for deployment. So just make sure your code run in notebook and then just export to reqirements.txt.

For streamlit community cloud, still not find workaround, AFAIK it can't handle dockerfile.

**Comment by tarun-aiplanet** [comment]
Interesting. @alvinrach if you don't mind, do you want to collaborate with our team on writing a blog on this?

We would be interested to share this on our Medium page regarding the deployment. Let me know if you are interested.

**Comment by alvinrach** [comment]
Sorry, I just saw your reply. I’m interested in collaborating on the blog post. Is this still open?

**Comment by alvinrach** [comment]
Sorry, I just saw your reply. I’m interested in collaborating on the blog post. Is this still open?

**Comment by alvinrach** [comment]
Sorry, I just saw your reply. Sure I’m interested in collaborating on the blog post. Is the opportunity still open?
