### ISSUE TITLE
[FEAT ADD]: Add Azure AI Search and Azure OpenAI Vector Store and Embeddings

### ISSUE THREAD

**Issue by farzad528** [aiplanethub/beyondllm#75]
https://learn.microsoft.com/azure/search/search-what-is-azure-search

**Comment by tarun-aiplanet** [comment]
Sure, you can create a PR for this feature. Happy to help

**Comment by tarun-aiplanet** [comment]
Assigned the feat add here: #29

Closing this issue. All the best.
